<a href="https://colab.research.google.com/github/pj0204/hello-world/blob/master/GuiaLesson3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Vamos a estudiar listas
lista = [12,43,78] #mismo  tipo de elementos - numeros enteros
lista2=['homero','marge','bart'] #cadenas de texto
lista3=['pepito',16,1.87] #diferentes tipos de datos
print(lista)
print(lista2)
print(lista3)

[12, 43, 78]
['homero', 'marge', 'bart']
['pepito', 16, 1.87]


In [0]:
nombres=['jose','martin','salvador']
edad=[43,56,49]
universidad=['ucsm','uni','pucp']
#acceder al primer elemento
print('el primer elemento de la lista nombres es ',nombres[0])
#longitud de una lista
print('la longitud de la lista nombres es ', len(nombres))

el primer elemento de la lista nombres es  jose
la longitud de la lista nombres es  3


In [0]:
#recorrer una lista
for i in range(3):
  print(i,nombres[i])

0 jose
1 martin
2 salvador


In [0]:
for j in range(len(nombres)):
  print(nombres[j],'tiene',edad[j],'años, y estudia en',universidad[j])

jose tiene 43 años, y estudia en ucsm
martin tiene 56 años, y estudia en uni
salvador tiene 49 años, y estudia en pucp


In [0]:
#añadir elementos a una lista
nombres.append('juanito')
edad.append(18)
universidad.append('de la vida')


In [0]:
print(nombres)
print(edad)
print(universidad)

['jose', 'martin', 'salvador', 'juanito']
[43, 56, 49, 18]
['ucsm', 'uni', 'pucp', 'de la vida']


In [0]:
#quiero saber el indice de un elemento
universidad.index('uni')

1

In [0]:
alumnos=['alice','bob','claudio','dionisio','erica','fiorela','gregorio']
calificacion=[19,18,10,14,14,20,12]

for i in range(len(calificacion)):
  #print(calificacion[i])  = < >
  if calificacion[i] < 14:
    print(alumnos[i],'desaprobado')
  else:
    print(alumnos[i],'aprobado')

#crear una lista de nombres
#crear una lista de apellidos
#edad
#corroborar si es mayor o menor de edad
# ruben tupayachi es mayor de edad
# jose perez es menor de edad

alice aprobado
bob aprobado
claudio desaprobado
dionisio aprobado
erica aprobado
fiorela aprobado
gregorio desaprobado


In [0]:
#LIBRERIA NUMPY
import numpy as np

V=np.array([1,2,3])
print(V)

S=np.array([3,4,5])
print(S)

[1 2 3]
[3 4 5]


In [0]:
#Operaciones
print(V+S)
#producto escalar 1*3 + 2*4 + 3*5
PE=V.dot(S)
print(PE)

[4 6 8]
26


In [0]:
#acceder a elementos
print(V[0])
print(S[1])

1
4


In [0]:
#Matrices 
A=np.array([[1,9,10],[7,12,21],[9,7,1]])
print('Esta es la matriz A')
print(A)

B=np.array([[3,4,34],[5,6,2],[1,2,3]])
print('esta es la matriz B')
print(B)

Esta es la matriz A
[[ 1  9 10]
 [ 7 12 21]
 [ 9  7  1]]
esta es la matriz B
[[ 3  4 34]
 [ 5  6  2]
 [ 1  2  3]]


In [0]:
#Elementos en A y B
print(A[1][0])
print(B[1][2])
#acceder a una fila
print(A[2])
print(B[0])
#acceder a una columna
print(B[:,2])

7
2
[9 7 1]
[ 3  4 34]
[34  2  3]


In [0]:
#operaciones con matrices
print('sumar A + B')
C=A+B
print(C)

sumar A + B
[[ 4 13 44]
 [12 18 23]
 [10  9  4]]


In [0]:
#producto de matrices
D=A.dot(B)
print(D)

[[ 58  78  82]
 [102 142 325]
 [ 63  80 323]]


In [0]:
#matriz identidad
print('esta es una matriz identidad')
I=np.eye(5)
print(I)

esta es una matriz identidad
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [0]:
#Arrays utiles
R=np.arange(-100,100,2) #valor iniciar - valor final - pasos
print('array usando arange')
print(R)
T=np.linspace(0,10,10)
print('array usando linspace')
print(T)

array usando arange
[-100  -98  -96  -94  -92  -90  -88  -86  -84  -82  -80  -78  -76  -74
  -72  -70  -68  -66  -64  -62  -60  -58  -56  -54  -52  -50  -48  -46
  -44  -42  -40  -38  -36  -34  -32  -30  -28  -26  -24  -22  -20  -18
  -16  -14  -12  -10   -8   -6   -4   -2    0    2    4    6    8   10
   12   14   16   18   20   22   24   26   28   30   32   34   36   38
   40   42   44   46   48   50   52   54   56   58   60   62   64   66
   68   70   72   74   76   78   80   82   84   86   88   90   92   94
   96   98]
array usando linspace
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
